const int led[]={13,12,11,10,9,8,7,6,};
int x=0;

void setup(){
  int i;

  
  for(i=0;i<=8;i++)  //for loop
  {
    pinMode(led[i],OUTPUT);
  }
}
void loop(){
    
    while(x==0){
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(100);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(200);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(250);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    delay(350);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(450);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(400);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(500);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    delay(500);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(500);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(500);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(50);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(50);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(50);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(50);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(75);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(75);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(75);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(150);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(200);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(300);
    digitalWrite(led[5], HIGH);
    delay(300);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], HIGH);
    delay(100);
    digitalWrite(led[2], LOW);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    delay(100);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    delay(100);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    delay(100);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    delay(100);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    delay(100);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    delay(100);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    delay(300);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(300);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(300);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(300);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    delay(300);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(75);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(75);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(75);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(150);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(200);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(300);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    delay(100);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[3], HIGH);
    delay(100);
    digitalWrite(led[4], LOW);
    digitalWrite(led[3], LOW);
    delay(100);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[3], HIGH);
    delay(100);
    digitalWrite(led[4], LOW);
    digitalWrite(led[3], LOW);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    delay(100);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(200);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(300);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(400);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(100);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[5], HIGH);
    delay(100);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    delay(100);
    digitalWrite(led[0], HIGH);
    digitalWrite(led[7], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(100);
    digitalWrite(led[2], LOW);
    digitalWrite(led[5], LOW);
    delay(100);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    delay(100);
    digitalWrite(led[0], LOW);
    digitalWrite(led[7], LOW);
    delay(100);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[2], HIGH);
    delay(100);
    digitalWrite(led[3], HIGH);
    delay(100);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[1], LOW);
    delay(100);
    digitalWrite(led[2], LOW);
    delay(100);
    digitalWrite(led[3], LOW);
    delay(100);
    digitalWrite(led[7], HIGH);
    delay(100);
    digitalWrite(led[6], HIGH);
    delay(100);
    digitalWrite(led[5], HIGH);
    delay(100);
    digitalWrite(led[4], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    delay(100);
    digitalWrite(led[6], LOW);
    delay(100);
    digitalWrite(led[5], LOW);
    delay(100);
    digitalWrite(led[4], LOW);
    delay(100);
    
    digitalWrite(led[0], HIGH);
    digitalWrite(led[7], HIGH);
    delay(100);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    delay(100);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[5], HIGH);
    delay(100);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(100);
    digitalWrite(led[2], LOW);
    digitalWrite(led[5], LOW);
    delay(100);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    delay(200);

    digitalWrite(led[1], HIGH);
    digitalWrite(led[3], HIGH);
    delay(200);
    digitalWrite(led[1], LOW);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[7], HIGH);
    delay(200);
    digitalWrite(led[4], LOW);
    digitalWrite(led[7], LOW);
    delay(100);
    
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(200);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[1], HIGH);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(300);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(200);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(100);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(200);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(200);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(200);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(100);
    digitalWrite(led[3],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    delay(100);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(100);
    digitalWrite(led[3],LOW);
    digitalWrite(led[4],LOW);
    delay(100);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(275);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[1],HIGH);
    delay(275);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[7],HIGH);
    delay(275);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[5],HIGH);
    delay(100);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(1200);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(100);
    digitalWrite(led[3],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    delay(100);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(200);
    digitalWrite(led[3],LOW);
    digitalWrite(led[4],LOW);
    delay(200);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(200);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(200);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(200);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    delay(200);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    delay(200);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    delay(200);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(100);

    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(100);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    delay(100);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    delay(100);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(200);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(200);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(500);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[3], HIGH);
    delay(200);
    digitalWrite(led[4], LOW);
    digitalWrite(led[3], LOW);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    delay(200);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(200);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(200);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(200);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[2], HIGH);
    delay(100);
    digitalWrite(led[3], HIGH);
    delay(100);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[1], LOW);
    delay(100);
    digitalWrite(led[2], LOW);
    delay(100);
    digitalWrite(led[3], LOW);
    delay(100);
    digitalWrite(led[7], HIGH);
    delay(100);
    digitalWrite(led[6], HIGH);
    delay(100);
    digitalWrite(led[5], HIGH);
    delay(100);
    digitalWrite(led[4], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    delay(100);
    digitalWrite(led[6], LOW);
    delay(100);
    digitalWrite(led[5], LOW);
    delay(100);
    digitalWrite(led[4], LOW);
    delay(100);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(300);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(300);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(300);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(300);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(300);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(500);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[3], HIGH);
    delay(100);
    digitalWrite(led[4], LOW);
    digitalWrite(led[3], LOW);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    delay(100);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    delay(100);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(100);
    digitalWrite(led[3],LOW);
    digitalWrite(led[4],LOW);
    delay(100);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(100);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    delay(100);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    delay(100);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    delay(100);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(100);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(100);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    delay(100);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    delay(100);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    delay(100);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    delay(100);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    delay(100);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    delay(100);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    delay(100);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    delay(100);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(100);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(100);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(100);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(100);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(500);
     digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[2], HIGH);
    delay(100);
    digitalWrite(led[3], HIGH);
    delay(100);
    digitalWrite(led[0], LOW);
    delay(100);
    digitalWrite(led[1], LOW);
    delay(100);
    digitalWrite(led[2], LOW);
    delay(100);
    digitalWrite(led[3], LOW);
    delay(100);
    digitalWrite(led[7], HIGH);
    delay(100);
    digitalWrite(led[6], HIGH);
    delay(100);
    digitalWrite(led[5], HIGH);
    delay(100);
    digitalWrite(led[4], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    delay(100);
    digitalWrite(led[6], LOW);
    delay(100);
    digitalWrite(led[5], LOW);
    delay(100);
    digitalWrite(led[4], LOW);
    delay(100);
     digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(100);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(100);
    digitalWrite(led[6], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    delay(100);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[3], HIGH);
    delay(100);
    digitalWrite(led[4], LOW);
    digitalWrite(led[3], LOW);
    delay(300);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(300);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(300);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(300);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(300);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(300);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(500);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(300);
    digitalWrite(led[0], HIGH);
    digitalWrite(led[1], HIGH);
    delay(400);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[7], HIGH);
    delay(400);
    digitalWrite(led[2], HIGH);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    digitalWrite(led[5], HIGH);
    delay(400);
    
    delay(100);digitalWrite(led[0], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[7],HIGH);
    delay(300);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[6],HIGH);
    delay(300);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[5],HIGH);
    delay(300);
    digitalWrite(led[3],HIGH);
    digitalWrite(led[4],HIGH);
    delay(300);
    digitalWrite(led[0], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    delay(200);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(75);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(75);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(75);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(150);
    digitalWrite(led[7],HIGH);
    digitalWrite(led[0],HIGH);
    digitalWrite(led[6],HIGH);
    digitalWrite(led[1],HIGH);
    digitalWrite(led[5],HIGH);
    digitalWrite(led[2],HIGH);
    digitalWrite(led[4],HIGH);
    digitalWrite(led[3],HIGH);
    delay(200);
    digitalWrite(led[7],LOW);
    digitalWrite(led[0],LOW);
    digitalWrite(led[6],LOW);
    digitalWrite(led[1],LOW);
    digitalWrite(led[5],LOW);
    digitalWrite(led[2],LOW);
    digitalWrite(led[4],LOW);
    digitalWrite(led[3],LOW);
    delay(200);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(100);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    delay(100);
    digitalWrite(led[3], HIGH);
    digitalWrite(led[4], HIGH);
    delay(200);
    digitalWrite(led[5], HIGH);
    digitalWrite(led[2], HIGH);
    delay(200);
    digitalWrite(led[6], HIGH);
    digitalWrite(led[1], HIGH);
    delay(300);
    digitalWrite(led[7], HIGH);
    digitalWrite(led[0], HIGH);
    delay(300);
    digitalWrite(led[3], LOW);
    digitalWrite(led[4], LOW);
    digitalWrite(led[5], LOW);
    digitalWrite(led[2], LOW);
    digitalWrite(led[1], LOW);
    digitalWrite(led[6], LOW);
    digitalWrite(led[7], LOW);
    digitalWrite(led[0], LOW);
    





    
    x++;
    }




}

